name: paxapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  barcode_scan2: ^4.2.3
  code_scan: ^0.4.8
  flutter:
    sdk: flutter
  flutter_zxing: ^1.1.0
  http: ^0.13.5
  pin_code_fields: ^7.4.0
  zxing_lib: ^0.9.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/