version: '3.8'

services:
  srv:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    command: air cmd/main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    ports:
      - 6599:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: